### DISCUSSION TITLE
Logging to Google Cloud Logging if running on Google Cloud

### DISCUSSION THREAD

**Discussion by treeder** [gochain-io/docs#141] [General]
Update the GoChain docker-compose.yml file and add the following under the `node:` service:

```yml
logging:
      driver: "gcplogs"
```

eg:

```yml
version: "3"
services:
  node:
    container_name: node
    image: gcr.io/gochain-core/gochain:${GOCHAIN_TAG:-stable}
    logging:
      driver: "gcplogs"
...
```
